version: '3.8'
services:
  selenium:
    image: seleniarm/standalone-chromium
    container_name: selenium-test-instance
    shm_size: 2g
    ports:
      - "4445:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  debugger:
    build: .
    container_name: debugger-test-instance
    env_file:
      - .env
    depends_on:
      - selenium
    command: python3 main_debug.py